<a href="https://colab.research.google.com/github/kritika966/AutoML-Using-PyCaret/blob/main/AutoML_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How To Fit a model with AutoML

## What is AutoML?

AutoML stands for Automated Machine Learning. It refers to techniques and tools that automatically build and optimize machine learning models without requiring deep expertise in data science.

**Key Features of AutoML:**

- Automatic data preprocessing (handling missing values, encoding)

- Feature engineering (creation & selection)

- Model training & selection (tries multiple models)

- Hyperparameter tuning (automatically adjusts model settings)

- Evaluation & comparison of models

- Model interpretability (e.g., SHAP, feature importance)


## Install Required Packages

In [ ]:
# Install PyCaret (compatible with Colab)
#!pip install --pre pycaret

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.3/46.3 kB 3.3 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of category-encoders to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 486.1/486.1 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.8/21.8 MB 55.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.4/85.4 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 18.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.9/51.9 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 77.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18

In [ ]:
# Import libraries
from pycaret.classification import *
import pandas as pd

In [ ]:
# Load the dataset

from google.colab import files
uploaded = files.upload()

Saving application_train.csv to application_train (1).csv


In [ ]:
df = pd.read_csv("application_train.csv")
df.head()

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N   
1      100003       0         Cash loans           F            N   
2      100004       0    Revolving loans           M            Y   
3      100006       0         Cash loans           F            N   
4      100007       0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5   
1               N             0          270000.0   1293502.5      35698.5   
2               Y             0           67500.0    135000.0       6750.0   
3               Y             0          135000.0    312682.5      29686.5   
4               Y             0          121500.0    513000.0      21865.5   

   ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                 0                0                0                0   
1  ...                 0                0                0                0   
2  ...                 0                0                0                0   
3  ...                 0                0                0                0   
4  ...                 0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        NaN                       NaN   
4                        0.0                       0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         NaN                        NaN   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        NaN                         NaN  
4                        0.0                         0.0  

[5 rows x 122 columns]

In [ ]:
df['TARGET'].value_counts(normalize=True)

TARGET
0    0.919271
1    0.080729
Name: proportion, dtype: float64

In [ ]:
df.isnull().sum().sort_values(ascending=False).head(10)

COMMONAREA_MEDI             214865
COMMONAREA_AVG              214865
COMMONAREA_MODE             214865
NONLIVINGAPARTMENTS_MODE    213514
NONLIVINGAPARTMENTS_AVG     213514
NONLIVINGAPARTMENTS_MEDI    213514
FONDKAPREMONT_MODE          210295
LIVINGAPARTMENTS_MODE       210199
LIVINGAPARTMENTS_AVG        210199
LIVINGAPARTMENTS_MEDI       210199
dtype: int64

In [ ]:
df.select_dtypes('object').nunique().sort_values(ascending=False).head(10)

ORGANIZATION_TYPE             58
OCCUPATION_TYPE               18
NAME_INCOME_TYPE               8
NAME_TYPE_SUITE                7
WEEKDAY_APPR_PROCESS_START     7
WALLSMATERIAL_MODE             7
NAME_FAMILY_STATUS             6
NAME_HOUSING_TYPE              6
NAME_EDUCATION_TYPE            5
FONDKAPREMONT_MODE             4
dtype: int64

## Initialize AutoML with PyCaret

In [ ]:
# Initialize PyCaret (AutoML)
clf = setup(data=df, target='TARGET', session_id=123, use_gpu=False)

## Compare Models

In [ ]:
# This will train and compare multiple models automatically
best_model = compare_models()


Initiated  . . . . . . . . . . . . . . . . . .              06:11:35
Status     . . . . . . . . . . . . . . . . . .      Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Ada Boost Classifier

Processing:   0%|          | 0/65 [00:00<?, ?it/s]

**Best Accuracy:**

All top models like Random Forest (0.9194) and Gradient Boosting (0.9195) perform similarly well.

But high accuracy alone is misleading if your data is imbalanced (e.g., very few positives).

**Best AUC (Class Separation):**

Gradient Boosting (0.7524) is best. AUC tells how well the model separates positive and negative classes.

Good when we care about ranking predictions.

**Best Recall (Catch Positives):**

QDA (0.9801) is highest — it catches almost all positives.

But its accuracy is very poor (0.1063), meaning it classifies too many negatives as positives (bad precision).

**Best Precision:**

Random Forest (0.7717) is best, meaning when it predicts positive, it's usually correct — but it barely catches any (recall = 0.0015).

**Best Balance (F1 Score):**

Gradient Boosting (0.0286) and Decision Tree (0.1533) do better than most, but all F1 scores are low.

Low F1 means models struggle to balance precision and recall.

**Fastest Models:**

Ridge Classifier (8.5 sec) and Naive Bayes (8.7 sec) are quick.

Good for quick testing, but not top performers in AUC or F1.

**Summary:**

Use AUC to compare models on imbalanced data.

If catching positives is critical (like in fraud/disease), go for high recall (like QDA).

If false alarms are bad, look for high precision (like Random Forest).

If you want a balanced model, go for one with higher F1 and AUC — in this case, Gradient Boosting is a safe choice.

## Create & Evaluate the Best Model

In [ ]:
# Finalize model
final_model = finalize_model(best_model)

# Evaluate model
evaluate_model(final_model)


interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

## Make Predictions

In [ ]:
# Predict on unseen data
predictions = predict_model(final_model)
predictions.head()

SK_ID_CURR NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
237042      374557         Cash loans           M            N   
226763      362659         Cash loans           F            N   
182044      311004         Cash loans           M            Y   
5214        106100         Cash loans           F            N   
290026      435994         Cash loans           F            N   

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
237042               N             0          225000.0    714154.5   
226763               Y             0          135000.0   1040985.0   
182044               Y             3          252000.0    900000.0   
5214                 Y             0           72000.0    113760.0   
290026               N             0           90000.0    414792.0   

        AMT_ANNUITY  AMT_GOODS_PRICE  ... FLAG_DOCUMENT_21  \
237042      21780.0         616500.0  ...                0   
226763      30438.0         909000.0  ...                0   
182044      31887.0         900000.0  ...                0   
5214         6480.0          90000.0  ...                0   
290026      18270.0         315000.0  ...                0   

       AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
237042                        0.0                       0.0   
226763                        0.0                       0.0   
182044                        0.0                       0.0   
5214                          0.0                       0.0   
290026                        0.0                       0.0   

       AMT_REQ_CREDIT_BUREAU_WEEK AMT_REQ_CREDIT_BUREAU_MON  \
237042                        0.0                       0.0   
226763                        0.0                       0.0   
182044                        0.0                       0.0   
5214                          0.0                       0.0   
290026                        0.0                       0.0   

        AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  TARGET  \
237042                        0.0                         1.0       0   
226763                        0.0                         4.0       0   
182044                        0.0                         0.0       0   
5214                          0.0                         1.0       0   
290026                        0.0                         1.0       0   

        prediction_label  prediction_score  
237042                 0            0.7988  
226763                 0            0.9656  
182044                 0            0.9680  
5214                   0            0.9692  
290026                 0            0.7841  

[5 rows x 124 columns]

This customer (ID: 374557) applied for a loan of 714,154.5 with an income of 225,000.0.

The actual label (TARGET) is 0, meaning the person did not default.

The model predicted 0 (no default) with a confidence score of 0.7988 (about 79.9%).

The prediction is correct. The model predicted "no default", and that was true.


The prediction_score is the model's confidence that the target is class 1 (default).

Closer to 1 = likely to default

Closer to 0 = likely to not default

Use prediction_label to make yes/no decisions, and use prediction_score to understand the model's confidence.



## Save Model

In [ ]:
# Save the model to use later
save_model(final_model, 'home_credit_best_model')

Transformation Pipeline and Model Successfully Saved


(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['SK_ID_CURR', 'CNT_CHILDREN',
                                              'AMT_INCOME_TOTAL', 'AMT_CREDIT',
                                              'AMT_ANNUITY', 'AMT_GOODS_PRICE',
                                              'REGION_POPULATION_RELATIVE',
                                              'DAYS_BIRTH', 'DAYS_EMPLOYED',
                                              'DAYS_REGISTRATION',
                                              'DAYS_ID_PUBLISH', 'OWN_CAR_AGE',
                                              'FLAG_MOBIL', 'FLAG_EMP_PHONE',
                                              'FLAG_WORK_...
                                             criterion='friedman_mse', init=None,
                                             learning_rate=0.1, loss='log_loss',
                                

## Automated Feature Engineering with PyCaret

PyCaret simplifies the process of feature engineering through its powerful `setup()` function, which automates many data preprocessing steps essential for building machine learning models. Here's a breakdown of what it does:

* **Missing Value Treatment**: PyCaret automatically detects and imputes missing data. It uses strategies like mean or median imputation for numerical columns and the most frequent value for categorical ones.

* **Categorical Encoding**: It seamlessly converts categorical variables into numerical format using appropriate encoding techniques such as one-hot encoding, ordinal encoding, or target-based encoding.

* **Outlier Handling**: The framework identifies and processes outliers by either modifying or excluding them to enhance model robustness.

* **Normalization and Scaling**: To ensure consistency across numerical features, PyCaret applies scaling techniques like standardization or normalization, improving model performance.

* **Feature Interaction Creation**: It can automatically generate new features by exploring interactions between existing variables, including polynomial transformations for capturing non-linear effects.

* **Reducing Dimensionality**: PyCaret helps in trimming down the number of input features while retaining the essential patterns, often using methods like PCA (Principal Component Analysis).

* **Feature Selection**: Through techniques like Recursive Feature Elimination (RFE), it filters out irrelevant or redundant features to streamline the dataset and optimize model accuracy.




## Conclusion

In this tutorial, we used PyCaret’s AutoML to quickly build and compare several classification models for predicting loan default risk. The Gradient Boosting Classifier performed best in terms of accuracy (91.97%) and precision (62.25%), but its recall was very low (1.26%), meaning it missed most actual defaulters.

We also explored individual predictions, showing how the model outputs both a prediction label (default or not) and a prediction score (model confidence). While the model is confident in predicting "no default", it struggles to correctly identify customers who actually default.

**This highlights the importance of:**

Evaluating multiple metrics, not just accuracy.

Understanding the business context — in credit risk, recall is critical to catch high-risk customers.

Using prediction scores to flag borderline or high-risk customers even if the model predicts no default.

With AutoML, we were able to build a baseline model quickly, interpret its performance, and understand how it makes decisions — a powerful tool for rapid experimentation in real-world business problems.